# -*- coding: utf-8 -*-
"""Weather 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_TE5XGEsjnWy9MLz1Tbvprq6C4Gueeph
"""

import requests
import pandas as pd
import numpy as np

API_Key = '2e5a087c82b5a359c56c5c23d9efbcb9'

api_add = f'https://api.openweathermap.org/data/2.5/onecall?lat=-33.87&lon=151.21&exclude=minutely,current&appid={API_Key}' 
json_data = requests.get(api_add).json()
data = json_data['hourly']

length = len(data)
speed_data = np.empty(length, dtype=float)
dir_data = speed_data = np.empty(length, dtype=int)
for i in range(length):
  wind_spd = json_data['hourly'][i]['wind_speed']
  wind_dir = json_data['hourly'][i]['wind_deg']
  speed_data[i] = wind_spd
  dir_data[i] = wind_dir

df_speed = pd.DataFrame(data = speed_data, columns=['wind speed in m/s'])
df_dir = pd.DataFrame(data = dir_data, columns=['wind direction in degrees'])

df_dir.head()